#ifndef INCLUDED_CMAKE_CONFIG_HPP_
#define INCLUDED_CMAKE_CONFIG_HPP_


#define PROJECT_VERSION "0.1.0"
#define PROJECT_VERSION_MAJOR "0"
#define PROJECT_VERSION_MINOR "1"
#define PROJECT_VERSION_PATCH "0"


#endif
