#ifndef INCLUDED_METAINFO_HPP_
#define INCLUDED_METAINFO_HPP_


#define PROJECT_VERSION "0.1.4"

#define PROJECT_VERSION_MAJOR "0"
#define PROJECT_VERSION_MINOR "1"
#define PROJECT_VERSION_PATCH "4"


#endif
