meevax: termios Class Reference
termios Class Reference
POSIX 標準ライブラリの構造体 termios の拡張クラス。
#include <termios.hpp>
Public Types
enum input_mode : unsigned int
端末ドライバの入力モードを示すフラグ値。型安全にビット幅演算可能。
enum effects
端末属性の変更を行う際の、変更がいつから効果を発揮するかを指定するためのフラグ値。
Public Member Functions
termios (decltype(fd_)::value_type fd)
TODO DOCUMENTATION.
~termios ()
TODO DOCUMENTATION.
void set_attrib (effects when=effects::from_now) const
元々 tcsetattr だったもの。名前を変えたことに特に深い意味はないがパッと見が呪文だったので変えた。
void change_to (input_mode mode)
TODO DOCUMENTATION.
Static Public Member Functions
static struct::termios get_attrib (int fd)
TODO DOCUMENTATION.
Private Attributes
const meevax::posix::fd fd_
TODO DOCUMENTATION.
const struct::termios initial_attrib_
TODO DOCUMENTATION.
Detailed Description
構造体 termios から派生しているため、termios.h 内の各関数の引数として指定可能。
現状は間に合わせの実装なのでカノニカルモードの設定くらいしかサポートしていない。
拡張であることを第一義とするため、使いやすくする以上のことはしない。
Definition at line 34 of file termios.hpp.
Member Enumeration Documentation
enum effects strong
元々、termios.h 内で optional_actions と呼ばれていたものだが、分かりにくいので変更した。
こちらではなく、when という名称も良いかなとは思ったが、文章になる方を選んだ。
詳細情報は The Linux Programming Interface pp.1358-1359 参照。
Enumerator
from_now
変更はその場ですぐに効果を発揮する。
after_drain
変更は現在キューイングされている出力をすべて端末に転送後に効果を発揮する。
after_flush
現在キューイングされている出力を破棄し、変更はその後すぐに効果を発揮する。
Definition at line 58 of file termios.hpp.
     {
          from_now = TCSANOW,
       after_drain = TCSADRAIN,
       after_flush = TCSAFLUSH,
     };
enum input_mode : unsigned int strong
主にメンバ関数 set_attrib への引数として用いる。
詳細情報は The Linux Programming Interface pp.1356-1357 参照。
Enumerator
canonical
端末からの入力を行単位に処理し、また行編集を可能とするモード。
noncanonical
端末からの入力を行単位にまとめないモード。
Definition at line 44 of file termios.hpp.
       : unsigned int
     {
          canonical = 1 << 0,
       noncanonical = 1 << 1,
     };
Constructor & Destructor Documentation
termios (decltype(fd_)::value_type fd) inline explicit
Definition at line 74 of file termios.hpp.
References termios::get_attrib().
       : fd_ {::isatty(fd) ? fd : throw std::system_error {errno, std::system_category()}},
         initial_attrib_ {get_attrib(fd_)}
     {}
~termios () inline
Definition at line 80 of file termios.hpp.
References termios::from_now.
     {
       ::tcsetattr(fd_, static_cast<std::underlying_type<effects>::type>(effects::from_now), &initial_attrib_);
     }
Member Function Documentation
void change_to (input_mode mode) inline
Definition at line 114 of file termios.hpp.
References termios::canonical, termios::from_now, termios::noncanonical, and termios::set_attrib().
     {
       switch (mode)
       {
       case meevax::posix::termios::input_mode::canonical:
         throw std::runtime_error {
           "[error] meevax::posix::termios::change_to() - unimplemented mode: canonical"
         };
       case meevax::posix::termios::input_mode::noncanonical:
         (*this).c_lflag &= ~(ICANON | ECHO);
         (*this).c_cc[VMIN]  = 1;
         (*this).c_cc[VTIME] = 0;
         set_attrib(effects::from_now);
         break;
       }
     }
static struct ::termios get_attrib (int fd) inline static
Definition at line 100 of file termios.hpp.
Referenced by termios::termios().
     {
       struct ::termios buffer {};
       if (const auto status {::tcgetattr(fd, &buffer)}; status < 0)
       {
         throw std::system_error {errno, std::system_category()};
       }
       else
       {
         return std::move(buffer);
       }
     }
void set_attrib (effects when = effects::from_now) const inline
Parameters
when 変更がいつから効力を発揮するかの指定。デフォルトは即座に発揮。
Definition at line 91 of file termios.hpp.
Referenced by termios::change_to().
     {
       if (const auto status {::tcsetattr(fd_, static_cast<std::underlying_type<effects>::type>(when), this)}; status < 0)
       {
         throw std::system_error {errno, std::system_category()};
       }
     }
Member Data Documentation
const meevax::posix::fd fd_ private
Definition at line 67 of file termios.hpp.
const struct ::termios initial_attrib_ private
Definition at line 70 of file termios.hpp.
The documentation for this class was generated from the following file:
meevax/posix/termios.hpp (a4b5a7a Clanup header dependency tree)