meevax: file_descriptor Class Reference
file_descriptor Class Reference
ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã®å®‰å…¨ãªç®¡ç†ã¨ã‚¢ã‚¯ã‚»ã‚¹ã‚’æä¾›ã™ã‚‹ã‚¯ãƒ©ã‚¹ã€‚ ãŸã ã® int fd ã§ã¯æˆ‘æ…¢ã§ããªããªã£ãŸã‹ã‚‰ä½œã£ãŸã€‚
#include <file_descriptor.hpp>
Public Types
using value_type = int
ãƒ¡ã‚¿é–¢æ•°ã®ãŸã‚ã®å‹å®šç¾©ã€‚POSIX ã‚·ã‚¹ãƒ†ãƒ ã®å®šã‚ã‚‹å‹ã€ã¤ã¾ã‚Š signed intã€‚
Public Member Functions
constexpr file_descriptor (value_type fd=invalid_value) noexcept
ã‚³ãƒ³ã‚¹ãƒˆãƒ©ã‚¯ã‚¿ã€‚
file_descriptor (file_descriptor &&moved) noexcept
ãƒ ãƒ¼ãƒ–ã‚³ãƒ³ã‚¹ãƒˆãƒ©ã‚¯ã‚¿ã€‚
~file_descriptor () noexcept
ãƒ‡ã‚¹ãƒˆãƒ©ã‚¯ã‚¿ã€‚ç®¡ç†ã—ã¦ã„ãŸãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã®å¾Œå§‹æœ«ã€‚
operator value_type () const noexcept
ã‚­ãƒ£ã‚¹ãƒˆæ¼”ç®—å­ã€‚é€šå¸¸ã¨åŒã˜ããƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿å€¤ã«ç”¨ãŒã‚ã‚‹éš›ã¯ã“ã¡ã‚‰ã‚’ã©ã†ãã€‚
operator bool () const noexcept
çœŸå½å€¤ã¸ã®ã‚­ãƒ£ã‚¹ãƒˆæ¼”ç®—å­ã€‚ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã¨ã—ã¦ã®æœ‰åŠ¹æ€§ã‚’ç¤ºã™ã€‚
value_type release () noexcept
ã“ã®ã‚¯ãƒ©ã‚¹ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆãŒç®¡ç†ã—ã¦ã„ãŸãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã‚’é–‹æ”¾ã™ã‚‹ã€‚ ã‚¯ãƒ­ãƒ¼ã‚ºã¯è¡Œã‚ãšã‚ãã¾ã§ç®¡ç†ä¸‹ã‹ã‚‰æ‰‹æ”¾ã™ã ã‘ã§ã‚ã‚‹ãŸã‚ã€ã‚¯ãƒ­ãƒ¼ã‚ºã«ã¯ file_descriptor::close ã‚’ç”¨ã„ã‚‹ã“ã¨ã€‚
void close () noexcept(false)
ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã‚’é–‰ã˜ã‚‹ã€‚ å‘¼ã°ã‚Œã‚‹å‰ã«ã‚»ãƒƒãƒˆã•ã‚Œã¦ã„ãŸãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã«å¯¾ã—ã¦ close ãŒå®Ÿè¡Œã•ã‚Œã€æ–°ãŸã«ç„¡åŠ¹å€¤ãŒã‚»ãƒƒãƒˆã•ã‚Œã‚‹ã€‚
decltype(auto) swap (file_descriptor &fd) noexcept
ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã®äº¤æ›ã€‚
decltype(auto) friend swap (file_descriptor &lhs, file_descriptor &rhs) noexcept
ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã®äº¤æ›ã€‚ã“ã¡ã‚‰ã¯æ¨™æº– swap ã¨ã®äº’æ›ã®ãŸã‚ã«å­˜åœ¨ã™ã‚‹ã€‚
decltype(auto) reset (value_type new_value) noexcept
ã“ã®ã‚¯ãƒ©ã‚¹ã®ç®¡ç†ã™ã‚‹ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã‚’æ–°ãŸã«è¨­å®šã—ç›´ã™ã€‚ å…ƒã€…ç®¡ç†ã—ã¦ã„ãŸãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã¯é–‰ã˜ã‚‰ã‚Œã‚‹ã€‚
bool is_tty ()
ä¸Šã®è‡ªèº«ã‚’å¯¾è±¡ã¨ã—ãŸã‚„ã¤ã€‚
Static Public Member Functions
static auto is_tty (value_type fd)
ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ãŒç«¯æœ«ã‚’å‚ç…§ã—ã¦ã„ã‚‹ã‹ã®çœŸå½å€¤ã‚’è¿”ã™ã€‚ ã‚¨ãƒ©ãƒ¼å†…å®¹ã‚’æ¡ã‚Šã¤ã¶ã—ã¦ã—ã¾ã£ã¦ã„ã‚‹ã®ãŒæ°—ã«é£Ÿã‚ãªã„ã®ã ãŒã€ã¾ã‚ã„ã„ã‹ã€‚
Public Attributes
value_type value
ã“ã®ã‚¯ãƒ©ã‚¹ãŒç®¡ç†ã™ã‚‹ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã®å€¤ã€‚private ã«ã—ã¦ãŠãã¹ãã‹ã€ã†ãƒ¼ã‚€ã€‚
Static Public Attributes
static constexpr value_type stdin { STDIN_FILENO}
æ¨™æº–å…¥åŠ›ã®ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿å€¤ã€‚æ•´æ•°å€¤ã®0ã€‚
static constexpr value_type stdout {STDOUT_FILENO}
æ¨™æº–å‡ºåŠ›ã®ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿å€¤ã€‚æ•´æ•°å€¤ã®1ã€‚
static constexpr value_type stderr {STDERR_FILENO}
æ¨™æº–ã‚¨ãƒ©ãƒ¼å‡ºåŠ›ã®ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿å€¤ã€‚æ•´æ•°å€¤ã®2ã€‚
static constexpr value_type invalid_value {-1}
ç„¡åŠ¹å€¤ã€‚åŸºæœ¬çš„ã«è² å€¤ãªã‚‰ã™ã¹ã¦ã‚¨ãƒ©ãƒ¼ã ãŒã€ã‚¯ãƒ©ã‚¹å†…éƒ¨ã§ã¯è² å€¤ã®ä»£è¡¨å€¤ã‚’ç”¨ã„ã‚‹ã“ã¨ã«ã™ã‚‹ã€‚
Detailed Description
æ”¾ã£ã¦ãŠã„ã¦ã‚‚å‹æ‰‹ã«ä¸Šæ‰‹ã„ã“ã¨é–‰ã˜ã¦ãã‚Œã‚‹ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ãŒã“ã‚Œã®ç›®æŒ‡ã™ã¨ã“ã‚ã€‚
ã“ã®ã‚¯ãƒ©ã‚¹ãŒç®¡ç†ã™ã‚‹ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ãŒã©ã®ã‚ˆã†ã«ä½¿ã‚ã‚Œã‚‹ã‹ã¯ã“ã®ã‚¯ãƒ©ã‚¹ãŒé–¢çŸ¥ã™ã‚‹ã¨ã“ã‚ã§ã¯ãªã„ã€‚
å…·ä½“çš„ã«ã¯ã€ã“ã®ã‚¯ãƒ©ã‚¹ã¯ãƒ¡ãƒ³ãƒé–¢æ•° close ã‚’æŒã£ã¦ã„ã‚‹ãŒ open ã‚’æŒã£ã¦ãªã„ã€‚
æœ€ä½é™ã®æ©Ÿèƒ½ã®ã¿ã‚’å®Ÿè£…ã—ã¦ã„ã‚‹ãŒã€ã‚¤ãƒ³ã‚¿ãƒ•ã‚§ãƒ¼ã‚¹ã¯ std::unique_ptr ã«å€£ã£ãŸã€‚
Definition at line 31 of file file_descriptor.hpp.
Member Typedef Documentation
using value_type = int
Definition at line 36 of file file_descriptor.hpp.
Constructor & Destructor Documentation
constexpr file_descriptor (value_type fd = invalid_value) inline noexcept
Parameters
fd ç®¡ç†å¯¾è±¡ã®ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿å€¤ã€‚
Definition at line 60 of file file_descriptor.hpp.
Referenced by file_descriptor::reset().
       : value {fd}
     {}
file_descriptor (file_descriptor && moved) inline explicit noexcept
Parameters
moved ãƒ ãƒ¼ãƒ–ã•ã‚Œã¦ãã‚‹ meevax::posix::file_descriptor å‹ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã€‚ è¢«ãƒ ãƒ¼ãƒ–ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆãŒç®¡ç†ã—ã¦ã„ãŸå€¤ã¯ã“ã¡ã‚‰ã«ç§»ç®¡ã•ã‚Œã‚‹ã€‚
Definition at line 71 of file file_descriptor.hpp.
       : value {moved.release()}
     {}
~file_descriptor () inline noexcept
Definition at line 76 of file file_descriptor.hpp.
References file_descriptor::close().
     {
       close();
     }
Member Function Documentation
void close () inline noexcept
Exceptions
ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿ã«å¯¾ã™ã‚‹ã‚¯ãƒ­ãƒ¼ã‚ºãŒå¤±æ•—ã—ãŸæ™‚ã€‚
Definition at line 113 of file file_descriptor.hpp.
References file_descriptor::invalid_value, and file_descriptor::release().
Referenced by file_descriptor::~file_descriptor().
     {
       if (invalid_value < value)
       {
         if (const auto status {::close(release())}; status < 0)
         {
           throw std::system_error {errno, std::system_category()};
         }
       }
     }
static auto is_tty (value_type fd) inline static
Definition at line 166 of file file_descriptor.hpp.
     {
       return ::isatty(fd) ? true : false;
     }
bool is_tty () inline
Definition at line 174 of file file_descriptor.hpp.
     {
       return is_tty(*this);
     }
operator bool () const inline noexcept
Definition at line 88 of file file_descriptor.hpp.
References file_descriptor::invalid_value, and file_descriptor::value.
     {
       return invalid_value < value;
     }
operator value_type () const inline noexcept
Definition at line 82 of file file_descriptor.hpp.
References file_descriptor::value.
     {
       return value;
     }
value_type release () inline noexcept
Returns
å…ƒã€…ä¿æŒã—ã¦ã„ãŸãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿å€¤ã€‚ ç„¡åŠ¹ã«ãªã£ã¦ã„ã‚‹ã‹ã‚‚ã—ã‚Œãªã„ã—ã€ã¾ã æœ‰åŠ¹ã‹ã‚‚ã—ã‚Œãªã„ã€‚
Definition at line 101 of file file_descriptor.hpp.
References file_descriptor::invalid_value.
Referenced by file_descriptor::close().
     {
       return std::exchange(value, invalid_value);
     }
decltype(auto) reset (value_type new_value) inline noexcept
Parameters
new_value æ–°ãŸã«è¨­å®šã•ã‚Œã‚‹ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‡ã‚£ã‚¹ã‚¯ãƒªãƒ—ã‚¿å€¤ã€‚
Returns
decltype(auto)
Definition at line 157 of file file_descriptor.hpp.
References file_descriptor::file_descriptor().
     {
       return file_descriptor(new_value).swap(*this);
     }
decltype(auto) swap (file_descriptor & fd) inline noexcept
Parameters
fd äº¤æ›å¯¾è±¡ã® meevax::posix::file_descriptor å‹ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã€‚
Returns
decltype(auto)
Definition at line 131 of file file_descriptor.hpp.
References file_descriptor::value.
     {
       return std::swap(value, fd.value);
     }
decltype(auto) friend swap (file_descriptor & lhs, file_descriptor & rhs) inline noexcept
Parameters
lhs å·¦è¾ºå€¤ã€‚
rhs å³è¾ºå€¤ã€‚
Returns
decltype(auto)
Definition at line 144 of file file_descriptor.hpp.
     {
       return lhs.swap(rhs);
     }
Member Data Documentation
constexpr value_type invalid_value {-1} static
Definition at line 49 of file file_descriptor.hpp.
Referenced by file_descriptor::close(), file_descriptor::operator bool(), and file_descriptor::release().
constexpr value_type stderr {STDERR_FILENO} static
Definition at line 46 of file file_descriptor.hpp.
constexpr value_type stdin { STDIN_FILENO} static
Definition at line 40 of file file_descriptor.hpp.
Referenced by main().
constexpr value_type stdout {STDOUT_FILENO} static
Definition at line 43 of file file_descriptor.hpp.
value_type value
Definition at line 52 of file file_descriptor.hpp.
Referenced by file_descriptor::operator bool(), file_descriptor::operator value_type(), and file_descriptor::swap().
The documentation for this class was generated from the following file:
meevax/posix/file_descriptor.hpp (a4b5a7a Clanup header dependency tree)