#ifndef INCLUDED_CMAKE_CONFIG_HPP_
#define INCLUDED_CMAKE_CONFIG_HPP_


#define PROJECT_VERSION "${PROJECT_VERSION}"
#define PROJECT_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}"
#define PROJECT_VERSION_MINOR "${PROJECT_VERSION_MINOR}"
#define PROJECT_VERSION_PATCH "${PROJECT_VERSION_PATCH}"


#endif
